version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: cve_alert_db
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
  fetcher:
    image: cve-alert-manager/fetcher
    build:
      context: .
      dockerfile: ./cve-alert-fetcher/Dockerfile
    environment:
      CVE_ALERT_MANAGER_CVEDATABASE_DATASOURCENAME: "user:password@tcp(db)/cve_alert_db"
    volumes:
      - ./config:/var/opt/cve-alert-manager
    depends_on:
      - db
  api:
    image: cve-alert-manager/api
    build:
      context: .
      dockerfile: ./cve-alert-restapi/
    restart: always
    environment:
      CVE_ALERT_MANAGER_CVEDATABASE_DATASOURCENAME: "user:password@tcp(db)/cve_alert_db"
    volumes:
      - ./config:/var/opt/cve-alert-manager
    depends_on:
      - db

volumes:
  data: