# official public key of CERT-BUND WID service (for verifying the received emails)
# see: https://www.cert-bund.de/wid-sig
certBundPublicKey: |
   -----BEGIN PGP PUBLIC KEY BLOCK-----
   Version: GnuPG v1

   mQINBGDjPwcBEADPS+6YnsUHMPYFMplU40DXYBEWiVuiQsw47bPvU7anS+3zpQeZ
   PtHubfwQOnrcvgLejlFONywU8xyKbGNOZpLHTgaokJSBogq6jY//RNGf/6AZxaMG
   0WIKQTkRqIYd119V2oFP2M+mTksFRH5qFAvgPFtjKvn7q9ldOSBJwKq+oy8gRSbC
   L9rA00poGi9dLWyRpLFAOov6J3K9+8DJSvtMl6vEpy97TmydtX6k0sXtVhG/u3To
   SfEPS6nLRf4KrVsiBLrpEJzbRQcFOz52Y1skbqV9ztxV+U5iHDaKPpEAUu2wsPn0
   Wdq2XVIX432PrDoNAygGECiw/4/uJQ5Q2QpOUuHb8IqrBUudM2KHpvIcncpQmv4g
   LhKzZ3MfeacAUu+0lQBG/Lox2BWmthlHlD9tIb96tSnAQSMMBYQIWceOsed76JQ2
   2gBH5+YReMNOi2GIwolK2xsYmfYVQ7lpB2Yorbk5gCsXzOaXnXX4JTnRahH61rKX
   GvV8m6oAKgBiedd66x6Idliy8BdQDtsbLSF/bylB2CsGIrsOccy+4U04xwKkaAEw
   9fN7Pe6nxgaCIC+aoxBQ1aGTYIer670iIZdiSJ7RUN+6pf6HXKciH854kWxIfEig
   0ErmFuABxyoeVIpR5hllQ09rH+dzQodZbPIeULtINO84E5CnjS7r/SLk+wARAQAB
   tCVDRVJULUJ1bmQgV0lEIDx3aWRAbWFpbC5jZXJ0LWJ1bmQuZGU+iQI9BBMBCAAn
   BQJg4z8HAhsDBQkFqjIABQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEAcL3Ohh
   E6HIPc8QAIMFcb7a6Elzd8jqHIultcWHziHoJARKXQbXFeK5+8OY8eWdAP5+QD+z
   0HAejnRU8tS/3qQRCvzhlMQvfq9HUNQDcviar59t04xu+ukRvavhh55yq15JvtJK
   qcxhir8egA3FmC2g28+fhrvpK921Bjbwg0jXZER1limE1PrDD3kdyo2kK237BYc6
   rFZCZl77xyvZg+BPPiSt11MWgNvNm9gMReEPTrLtLDPyr29ed6SIgDPKKeIE3A3/
   i2g3znoUyA534ahhSr9/9RceAnFJxLUuOswlZRcqhGNLU/dSW00YDZeBNXhs0K76
   Z6IXL6EFbGgqGg4FDE05S77ZFbUWijcUAdx8RjdZudHBKrKHGE2LzMDTr6pxmemy
   xNGXhporpuN0OQwn/SEXzBN3rTpyw7V9/9RdL2ph+DyzyRY+QRdNgBKkpvH8Wo/5
   8HenRDuJIowTNo8b1OXfzwcgAxSW1Wd6QhC2bj+J1PhUC9My8wWaUXSn1u9VmuWA
   W0AJUfNTPePoOeJ3/2EhDHyzbeuEPfEGTUczBfjUNRh+S1TNKJEdMjo/b4fmuheI
   uIIGqYKjweqD2n4m0I0Cssw72dRZRejqkCRcyH85bdp3qtSztjW/aYrRKNW4Vczb
   kMIjB/aqMk2WQPVzTA7TS7mgvd6fU74eecBXPVY8anLjSQGEkZ1c
   =EVyk
   -----END PGP PUBLIC KEY BLOCK-----

# POP3 account credentials to received CERT-BUND WID emails
certBundPop3:
   # POP3 username
   username: user
   # POP3 password
   password: pass
   # POP3 hostname:port
   host: localhost:110

# logging settings
logging:
   # logging to syslog
   syslog: false
   # facility to log to
   # all valid facilities are listed in the go doc of the syslog package
   facility: local0

# CVE database to store/read the CVE cases
cveDatabase:
   # database driver
   driverName: mysql
   # DSN
   dataSourceName: "user:password@/cve_alert_db"

# Settings for the restAPI
restApi:
   username: user
   password: pass
   port: 1323

# Daemon mode for the fetcher
daemon: false

# Option to activate tls
tls: false